"""One shared-artifact BR-16a chain from M00 through M11 learner entrypoints."""
import json
import hashlib
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BOT_DIR = ROOT / "lab/affiliate-bot"
REGISTRY = ROOT / "lab/mission-runtime/testdata/m07-registry.json"


def run(command, cwd=ROOT, expected=0, env=None):
    result = subprocess.run([str(x) for x in command], cwd=cwd, text=True, capture_output=True, env=env)
    if result.returncode != expected:
        raise AssertionError((command, result.stdout, result.stderr))
    return result


def invoke(bot, *args, expected=0, env=None):
    result = run([bot, *args], expected=expected, env=env)
    return json.loads(result.stdout)


def write_cost_bound(path, intent, amount, expires_at, bound_id):
    payload = {
        "cost_bound_id": bound_id, "intent_id": intent["intent_id"], "intent_hash": intent["intent_hash"],
        "max_cost_minor": amount, "currency": "USD", "source_ref": "fixture:br16-cost-registry",
        "observed_at": "2026-09-07T01:06:00Z", "expires_at": expires_at,
        "correlation_id": intent["correlation_id"], "hash_version": "go-json-v1",
    }
    digest = hashlib.sha256(json.dumps(payload, separators=(",", ":"), ensure_ascii=False).encode()).hexdigest()
    payload["cost_bound_hash"] = "sha256:" + digest
    path.write_text(json.dumps(payload), encoding="utf-8")


def write_canary_grant(path, intent, policy, approval, max_executions, max_cost):
    payload = {
        "grant_id": "br16-g", "grant_version": "v1", "policy_version": policy["policy_version"],
        "approval_ref": approval["approval_id"], "approved_by": "human", "approver_id": approval["approver_id"],
        "approved_at": approval["approved_at"], "valid_from": approval["approved_at"], "expires_at": approval["expires_at"],
        "allowed_risk_classes": [policy["risk_class"]], "allowed_action_types": [intent["action_type"]], "allowed_hosts": ["example.com"],
        "executor_ids": ["local_sandbox"], "max_executions_total": max_executions, "max_executions_per_window": max_executions,
        "window_seconds": 3600, "max_cost_minor_total": max_cost, "currency": "USD", "max_pending_outcomes": 1,
        "kill_switch_required": True, "correlation_id": intent["correlation_id"], "hash_version": "go-json-v1",
    }
    payload["grant_hash"] = "sha256:" + hashlib.sha256(json.dumps(payload, separators=(",", ":"), ensure_ascii=False).encode()).hexdigest()
    path.write_text(json.dumps(payload), encoding="utf-8")


def grounded_claim(field, value, evidence_id):
    value = json.loads(json.dumps(value, separators=(',', ':'), ensure_ascii=False, sort_keys=True))
    rendered = f"{field}={json.dumps(value, separators=(',', ':'), ensure_ascii=False, sort_keys=True)} [evidence:{evidence_id}]"
    return rendered, {"text": rendered, "field_or_claim": field, "value": value, "evidence_ids": [evidence_id]}


def main():
    go = shutil.which(os.environ.get("GO_BIN", "go")) or os.environ.get("GO_BIN", "go")
    with tempfile.TemporaryDirectory(prefix="br16a-shared-") as directory:
        work = Path(directory); bot = work / "bot"; env = dict(os.environ, GOWORK="off", GOCACHE=str(work / "go-cache"))
        run([go, "build", "-o", bot, "./cmd/bot"], BOT_DIR, env=env)
        history, observations, model = [work / name for name in ("history.jsonl", "observations.json", "model.json")]
        tool_result, registered_tool = work / "tool-result.json", work / "registered-tool-result.json"
        action, actions = work / "action.json", work / "actions.jsonl"
        outcome, outcomes = work / "outcome.json", work / "outcomes.jsonl"
        evaluations, proposals, reviews = [work / name for name in ("evaluations.jsonl", "proposals.jsonl", "reviews.jsonl")]
        # M00 output is consumed by M02, not regenerated by the next smoke.
        imported = invoke(bot, "evidence", "import", ROOT / "examples/m00-import/packet-t2.json", env=env)["artifact"]
        observations.write_text(json.dumps(imported), encoding="utf-8")
        assert "APPENDED" in run([bot, "history", "capture", history, observations, "br16-d", "2026-09-03T00:00:00Z", "2026-09-03T00:00:00Z"], env=env).stdout
        context = invoke(bot, "m07", "context", history, "br16-d")["artifact"]
        evidence_id = context["evidence_ids"][0]
        evidence = next(item for item in context["evidence"] if item["evidence_id"] == evidence_id)
        # Synthetic adapter fixture: registration must happen before the model
        # can cite the returned body, even in this offline shared workspace.
        tool_result.write_text(json.dumps({"record_id":"br16-d","tool_call":{"tool_name":"public_http","method":"GET","target":"https://example.com/a"},"status_code":200,"received_at":"2026-09-03T00:01:00Z","redirected":False,"body":{"fixture_price":100}}), encoding="utf-8")
        registration = invoke(bot, "m07", "register-tool-result", history, "br16-d", REGISTRY, tool_result, registered_tool)
        assert registration["status"] == "APPENDED"
        tool_evidence = registration["artifact"]["evidence"]
        answer, claim = grounded_claim(tool_evidence["field_or_claim"], tool_evidence["value"], tool_evidence["evidence_id"])
        model.write_text(json.dumps({"state":"HUMAN_REVIEW","answer":answer,"claims":[claim],"evidence_ids":[tool_evidence["evidence_id"]],"tool_calls":[],"authority":"A2-RO","write_permission":False}), encoding="utf-8")
        assert invoke(bot, "m07", "validate", history, "br16-d", model, REGISTRY, registered_tool)["status"] == "VALID"
        action.write_text(json.dumps({"action_id":"br16-a","decision_id":"br16-d","action_type":"synthetic_manual","target":"fixture:br16","performed_by":"human","performed_at":"2026-09-04T00:00:00Z","measurement_window_end":"2026-09-05T00:00:00Z","compliance_reviewed":True}), encoding="utf-8")
        assert invoke(bot, "action", "record", history, actions, action)["status"] == "APPENDED"
        outcome.write_text(json.dumps({"outcome_id":"br16-o","effect_ref":{"effect_kind":"HUMAN_ACTION","effect_id":"br16-a"},"observed_at":"2026-09-05T00:00:00Z","status":"PENDING","metrics":{},"source_ref":"fixture:br16"}), encoding="utf-8")
        assert invoke(bot, "outcome", "import", history, actions, outcomes, outcome)["status"] == "APPENDED"
        config = work / "evaluation.json"; config.write_text(json.dumps({"evaluation_id":"br16-e","decision_id":"br16-d","effect_ref":{"effect_kind":"HUMAN_ACTION","effect_id":"br16-a"},"outcome_ids":["br16-o"],"evaluated_at":"2026-09-06T00:00:00Z"}), encoding="utf-8")
        assert invoke(bot, "evaluation", "create", history, actions, outcomes, evaluations, config)["status"] == "APPENDED"

        # The subsequent M08 intent must come from the persisted M07 proposal,
        # not a caller-declared human intent or a replacement target.
        proposal_model, agent_proposal = work / "agent-model.json", work / "agent-proposal.json"
        proposal_answer, proposal_claim = grounded_claim(evidence["field_or_claim"], evidence["value"], evidence_id)
        proposal_model.write_text(json.dumps({"state":"HUMAN_REVIEW","answer":proposal_answer,"claims":[proposal_claim],"evidence_ids":[evidence_id],"tool_calls":[],"authority":"A2-RO","write_permission":False,"proposed_action":{"action_type":"DRAFT","target":"https://example.com/draft","parameters":{"id":9007199254740993}}}), encoding="utf-8")
        proposal = invoke(bot, "m07", "register-proposal", history, "br16-d", proposal_model, REGISTRY, agent_proposal)
        assert proposal["status"] == "APPENDED"
        proposal_id = proposal["artifact"]["proposal_id"]
        request = work / "intent-request.json"; intent = work / "intent.json"; policy_config = work / "policy.json"; policy = work / "policy-output.json"; state = work / "runtime"
        request.write_text(json.dumps({"intent_id":"br16-i","decision_id":"br16-d","evidence_ids":[evidence_id],"action_type":"DRAFT","target":"https://example.com/draft","parameters":{"id":9007199254740993},"proposed_by":"agent","proposal_ref":proposal_id,"created_at":"2026-09-07T00:00:00Z","expires_at":"2099-09-03T03:00:00Z","correlation_id":"br16-c","idempotency_key":"br16-k"}), encoding="utf-8")
        tampered_request = work / "intent-request-tampered.json"
        tampered_request.write_text(request.read_text(encoding="utf-8").replace("https://example.com/draft", "https://example.com/changed"), encoding="utf-8")
        assert invoke(bot, "mission", "m08-intent", history, tampered_request, agent_proposal, work / "tampered-intent.json", expected=1)["status"] == "REJECTED"
        assert invoke(bot, "mission", "m08-intent", history, request, agent_proposal, intent)["status"] == "APPENDED"
        policy_config.write_text(json.dumps({"policy_version":"br16-v1","now":"2026-09-07T01:00:00Z","allowed_hosts":["example.com"],"action_risk":{"DRAFT":"RISK0"},"seen_idempotency":{}}), encoding="utf-8")
        assert invoke(bot, "mission", "m08-policy", history, intent, policy_config, agent_proposal, policy)["status"] == "ALLOW"
        assert invoke(bot, "mission", "bind", state, intent, policy)["status"] == "BOUND"
        i = json.loads(intent.read_text()); p = json.loads(policy.read_text())
        approval = work / "approval.json"; approval.write_text(json.dumps({"approval_id":"br16-ap","intent_id":i["intent_id"],"intent_hash":i["intent_hash"],"policy_version":p["policy_version"],"decision":"APPROVE","approved_by":"human","approver_id":"pilot-human","approved_at":"2026-09-07T01:05:00Z","expires_at":"2099-09-03T02:50:00Z","correlation_id":i["correlation_id"],"one_time":True}), encoding="utf-8")
        assert invoke(bot, "mission", "m09-approval", state, approval)["status"] == "ACK"
        grant = work / "grant.json"; write_canary_grant(grant, i, p, json.loads(approval.read_text()), 1, 100)
        assert invoke(bot, "mission", "m10-canary", state, grant)["status"] == "ACK"
        cost = work / "cost-bound.json"; write_cost_bound(cost, i, 100, "2099-09-03T02:45:00Z", "br16-cost")
        assert invoke(bot, "mission", "m10-reserve", state, cost, "unregistered", expected=1)["status"] == "REJECTED"
        assert invoke(bot, "mission", "m10-cost-register", state, cost)["status"] == "APPENDED"
        assert invoke(bot, "mission", "m10-cost-register", state, cost)["status"] == "EXACT_DUPLICATE"
        gate = work / "canary-gate.json"
        gate_time = "2026-09-08T00:00:00Z"
        gate_response = invoke(bot, "mission", "m10-gate", state, cost, gate, gate_time)
        assert gate_response["status"] == "ALLOW_CANARY" and gate_response["artifact"]["execution_authorized"] is False
        assert invoke(bot, "mission", "m10-gate", state, cost, gate, gate_time)["status"] == "EXACT_DUPLICATE"
        forged_gate = work / "forged-canary-gate.json"
        forged_gate_data = json.loads(gate.read_text(encoding="utf-8")); forged_gate_data["gate_id"] = "gate-forged-but-schema-valid"
        forged_gate.write_text(json.dumps(forged_gate_data), encoding="utf-8")
        assert invoke(bot, "mission", "m10-authorize", state, cost, forged_gate, work / "forged-authorization.json", gate_time, "local_sandbox", expected=1)["status"] == "REJECTED"
        authorization = work / "canary-authorization.json"
        authorization_response = invoke(bot, "mission", "m10-authorize", state, cost, gate, authorization, gate_time, "local_sandbox")
        assert authorization_response["status"] == "AUTHORIZED" and authorization_response["artifact"]["execution_authorized"] is True
        assert invoke(bot, "mission", "m10-authorize", state, cost, gate, authorization, gate_time, "local_sandbox")["status"] == "EXACT_DUPLICATE"
        cancelled = work / "cancelled-execution.json"
        forged_authorization = work / "forged-authorization.json"
        forged_authorization_data = json.loads(authorization.read_text(encoding="utf-8")); forged_authorization_data["authorization_id"] = "canary-auth-forged-but-schema-valid"
        forged_authorization.write_text(json.dumps(forged_authorization_data), encoding="utf-8")
        assert invoke(bot, "mission", "m10-cancel", state, forged_authorization, work / "forged-execution.json", "2026-09-08T00:01:00Z", "must-not-resolve-forged-authorization", expected=1)["status"] == "REJECTED"
        cancellation = invoke(bot, "mission", "m10-cancel", state, authorization, cancelled, "2026-09-08T00:01:00Z", "learner-cancelled-before-executor")
        assert cancellation["status"] == "APPENDED" and cancellation["artifact"]["status"] == "CANCELLED" and cancellation["artifact"]["side_effect_state"] == "NOT_PERFORMED"
        assert invoke(bot, "mission", "m10-cancel", state, authorization, cancelled, "2026-09-08T00:01:00Z", "learner-cancelled-before-executor")["status"] == "EXACT_DUPLICATE"
        resolved = invoke(bot, "mission", "m10-resolve", state, "EXECUTION_RECORD", cancellation["artifact"]["execution_id"])
        assert resolved["status"] == "RESOLVED" and resolved["artifact"] == cancellation["artifact"]
        assert invoke(bot, "mission", "m10-resolve", state, "EXECUTION_RECORD", "canary-exec-not-registered", expected=1)["status"] == "REJECTED"
        artifact_kinds = {entry["artifact_kind"] for entry in map(json.loads, (state / "m10-artifacts.jsonl").read_text(encoding="utf-8").splitlines()) if entry}
        assert {"CANARY_GRANT", "TRUSTED_COST_BOUND", "CANARY_GATE", "EXECUTION_AUTHORIZATION", "EXECUTION_RECORD"}.issubset(artifact_kinds)
        tampered = work / "cost-bound-tampered.json"; tampered.write_text(cost.read_text().replace('"max_cost_minor": 100', '"max_cost_minor": 1'), encoding="utf-8")
        assert invoke(bot, "mission", "m10-gate", state, tampered, work / "tampered-gate.json", gate_time, expected=1)["status"] == "REJECTED"
        assert invoke(bot, "mission", "m10-reserve", state, tampered, "tampered", expected=1)["status"] == "REJECTED"
        expired = work / "cost-bound-expired.json"; write_cost_bound(expired, i, 100, "2026-09-07T01:07:00Z", "br16-expired")
        assert invoke(bot, "mission", "m10-cost-register", state, expired, expected=1)["status"] == "REJECTED"
        # Two independent processes race for the single execution/cost budget.
        # The directory lock may make one return BUSY; retrying it must then see
        # the committed budget and cannot create a second reservation.
        attempts = [
            subprocess.Popen([str(bot), "mission", "m10-reserve", str(state), str(cost), reservation], cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env)
            for reservation in ("br16-r1", "br16-r2")
        ]
        responses = {}
        for reservation, process in zip(("br16-r1", "br16-r2"), attempts):
            stdout, stderr = process.communicate()
            if process.returncode not in (0, 1):
                raise AssertionError((stdout, stderr))
            responses[reservation] = json.loads(stdout)
        assert sum(response["status"] == "RESERVED" for response in responses.values()) == 1
        assert all(response["status"] in {"RESERVED", "BUSY", "BUDGET_DENIED"} for response in responses.values())
        winner = next(reservation for reservation, response in responses.items() if response["status"] == "RESERVED")
        loser = "br16-r2" if winner == "br16-r1" else "br16-r1"
        assert invoke(bot, "mission", "m10-canary", state, grant)["artifact"]["executions_used"] == 1
        assert invoke(bot, "mission", "m10-reserve", state, cost, winner)["status"] == "EXACT_DUPLICATE"
        assert invoke(bot, "mission", "m10-canary", state, grant)["artifact"]["executions_used"] == 1
        assert invoke(bot, "mission", "m10-reserve", state, cost, loser, expected=1)["status"] == "BUDGET_DENIED"
        assert invoke(bot, "mission", "m10-authorize", state, cost, gate, work / "stale-authorization.json", gate_time, "local_sandbox", expected=1)["status"] == "REJECTED"
        assert invoke(bot, "mission", "m11-stop", state, "br16a-restart-drill")["status"] == "STOPPED"
        # New process, same workspace: replay and durable stop must survive.
        assert "replay=MATCH" in run([bot, "history", "replay", history]).stdout
        status = invoke(bot, "mission", "status", state)
        assert status["artifact"]["stop"] is True
        assert invoke(bot, "mission", "m10-canary", state, grant, expected=1)["status"] == "STOPPED"
        assert invoke(bot, "mission", "init", state, expected=1)["status"] == "ALREADY_INITIALIZED"
    print("BR-16a PASS: one shared workspace, M00→M11 artifacts, real M07 validation, restart/replay and durable STOP")


if __name__ == "__main__":
    main()
