"""One shared-artifact BR-16a chain from M00 through M11 learner entrypoints."""
import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BOT_DIR = ROOT / "lab/affiliate-bot"
REGISTRY = ROOT / "lab/mission-runtime/testdata/m07-registry.json"


def run(command, cwd=ROOT, expected=0, env=None):
    result = subprocess.run([str(x) for x in command], cwd=cwd, text=True, capture_output=True, env=env)
    if result.returncode != expected:
        raise AssertionError((command, result.stdout, result.stderr))
    return result


def invoke(bot, *args, expected=0, env=None):
    result = run([bot, *args], expected=expected, env=env)
    return json.loads(result.stdout)


def main():
    go = shutil.which(os.environ.get("GO_BIN", "go")) or os.environ.get("GO_BIN", "go")
    with tempfile.TemporaryDirectory(prefix="br16a-shared-") as directory:
        work = Path(directory); bot = work / "bot"; env = dict(os.environ, GOWORK="off", GOCACHE=str(work / "go-cache"))
        run([go, "build", "-o", bot, "./cmd/bot"], BOT_DIR, env=env)
        history, observations, model = [work / name for name in ("history.jsonl", "observations.json", "model.json")]
        action, actions = work / "action.json", work / "actions.jsonl"
        outcome, outcomes = work / "outcome.json", work / "outcomes.jsonl"
        evaluations, proposals, reviews = [work / name for name in ("evaluations.jsonl", "proposals.jsonl", "reviews.jsonl")]
        # M00 output is consumed by M02, not regenerated by the next smoke.
        imported = invoke(bot, "evidence", "import", ROOT / "examples/m00-import/packet-t2.json", env=env)["artifact"]
        observations.write_text(json.dumps(imported), encoding="utf-8")
        assert "APPENDED" in run([bot, "history", "capture", history, observations, "br16-d", "2026-09-03T00:00:00Z", "2026-09-03T00:00:00Z"], env=env).stdout
        context = invoke(bot, "m07", "context", history, "br16-d")["artifact"]
        evidence_id = context["evidence_ids"][0]
        evidence = next(item for item in context["evidence"] if item["evidence_id"] == evidence_id)
        model.write_text(json.dumps({"state":"HUMAN_REVIEW","answer":"The supplied product snapshot is synthetic and limited.","claims":[{"text":"The supplied product snapshot is synthetic and limited.","field_or_claim":evidence["field_or_claim"],"value":evidence.get("value"),"evidence_ids":[evidence_id]}],"evidence_ids":[evidence_id],"tool_calls":[],"authority":"A2-RO","write_permission":False}), encoding="utf-8")
        assert invoke(bot, "m07", "validate", history, "br16-d", model, REGISTRY)["status"] == "VALID"
        action.write_text(json.dumps({"action_id":"br16-a","decision_id":"br16-d","action_type":"synthetic_manual","target":"fixture:br16","performed_by":"human","performed_at":"2026-09-04T00:00:00Z","measurement_window_end":"2026-09-05T00:00:00Z","compliance_reviewed":True}), encoding="utf-8")
        assert invoke(bot, "action", "record", history, actions, action)["status"] == "APPENDED"
        outcome.write_text(json.dumps({"outcome_id":"br16-o","effect_ref":{"effect_kind":"HUMAN_ACTION","effect_id":"br16-a"},"observed_at":"2026-09-05T00:00:00Z","status":"PENDING","metrics":{},"source_ref":"fixture:br16"}), encoding="utf-8")
        assert invoke(bot, "outcome", "import", history, actions, outcomes, outcome)["status"] == "APPENDED"
        config = work / "evaluation.json"; config.write_text(json.dumps({"evaluation_id":"br16-e","decision_id":"br16-d","effect_ref":{"effect_kind":"HUMAN_ACTION","effect_id":"br16-a"},"outcome_ids":["br16-o"],"evaluated_at":"2026-09-06T00:00:00Z"}), encoding="utf-8")
        assert invoke(bot, "evaluation", "create", history, actions, outcomes, evaluations, config)["status"] == "APPENDED"

        request = work / "intent-request.json"; intent = work / "intent.json"; policy_config = work / "policy.json"; policy = work / "policy-output.json"; state = work / "runtime"
        request.write_text(json.dumps({"intent_id":"br16-i","decision_id":"br16-d","evidence_ids":[evidence_id],"action_type":"DRAFT","target":"https://example.com/draft","parameters":{},"proposed_by":"human","created_at":"2026-09-07T00:00:00Z","expires_at":"2099-09-03T03:00:00Z","correlation_id":"br16-c","idempotency_key":"br16-k"}), encoding="utf-8")
        assert invoke(bot, "mission", "m08-intent", history, request, intent)["status"] == "APPENDED"
        policy_config.write_text(json.dumps({"policy_version":"br16-v1","now":"2026-09-07T01:00:00Z","allowed_hosts":["example.com"],"action_risk":{"DRAFT":"RISK0"},"seen_idempotency":{}}), encoding="utf-8")
        assert invoke(bot, "mission", "m08-policy", intent, policy_config, policy)["status"] == "ALLOW"
        assert invoke(bot, "mission", "bind", state, intent, policy)["status"] == "BOUND"
        i = json.loads(intent.read_text()); p = json.loads(policy.read_text())
        approval = work / "approval.json"; approval.write_text(json.dumps({"approval_id":"br16-ap","intent_id":i["intent_id"],"intent_hash":i["intent_hash"],"policy_version":p["policy_version"],"decision":"APPROVE","approved_by":"human","approver_id":"pilot-human","approved_at":"2026-09-07T01:05:00Z","expires_at":"2099-09-03T02:50:00Z","correlation_id":i["correlation_id"],"one_time":True}), encoding="utf-8")
        assert invoke(bot, "mission", "m09-approval", state, approval)["status"] == "ACK"
        grant = work / "grant.json"; grant.write_text(json.dumps({"grant_id":"br16-g","max_executions":1,"max_cost_minor":100,"currency":"USD"}), encoding="utf-8")
        assert invoke(bot, "mission", "m10-canary", state, grant)["status"] == "ACK"
        assert invoke(bot, "mission", "m10-reserve", state, "100")["status"] == "RESERVED"
        assert invoke(bot, "mission", "m10-canary", state, grant)["artifact"]["executions_used"] == 1
        assert invoke(bot, "mission", "m10-reserve", state, "1", expected=1)["status"] == "BUDGET_DENIED"
        assert invoke(bot, "mission", "m11-stop", state, "br16a-restart-drill")["status"] == "STOPPED"
        # New process, same workspace: replay and durable stop must survive.
        assert "replay=MATCH" in run([bot, "history", "replay", history]).stdout
        status = invoke(bot, "mission", "status", state)
        assert status["artifact"]["stop"] is True
        assert invoke(bot, "mission", "m10-canary", state, grant, expected=1)["status"] == "STOPPED"
        assert invoke(bot, "mission", "init", state, expected=1)["status"] == "ALREADY_INITIALIZED"
    print("BR-16a PASS: one shared workspace, M00→M11 artifacts, real M07 validation, restart/replay and durable STOP")


if __name__ == "__main__":
    main()
